# Generated by Django 6.0.7 on 2026-08-02 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_director_movie_director'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='director',
        ),
    ]
