# Generated by Django 5.0.7 on 2026-08-22 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(max_length=30, unique=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='invoices/')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='orders.order')),
            ],
            options={
                'db_table': 'invoices',
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('razorpay_order_id', models.CharField(db_index=True, max_length=100)),
                ('razorpay_payment_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('razorpay_signature', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('method', models.CharField(choices=[('UPI', 'UPI'), ('CARD', 'Card'), ('NETBANKING', 'Net Banking'), ('WALLET', 'Wallet'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('status', models.CharField(choices=[('CREATED', 'Order created, awaiting payment'), ('VERIFIED', 'Signature verified — payment successful'), ('FAILED', 'Payment failed'), ('SIGNATURE_MISMATCH', 'Signature verification failed'), ('REFUNDED', 'Refunded')], default='CREATED', max_length=30)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='orders.order')),
            ],
            options={
                'db_table': 'payment_transactions',
                'indexes': [models.Index(fields=['order', 'status'], name='payment_tra_order_i_650087_idx')],
            },
        ),
    ]
