# Generated by Django 5.0.7 on 2026-08-22 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_type', models.CharField(choices=[('REGISTRATION', 'Registration welcome'), ('EMAIL_VERIFICATION', 'Email verification'), ('PASSWORD_RESET', 'Password reset'), ('ORDER_CONFIRMATION', 'Order confirmation'), ('PAYMENT_RECEIPT', 'Payment receipt'), ('SHIPMENT_TRACKING', 'Shipment tracking'), ('DELIVERY_CONFIRMATION', 'Delivery confirmation'), ('LOW_STOCK_ALERT', 'Admin low stock alert')], max_length=30)),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('was_successful', models.BooleanField(default=True)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='orders.order')),
            ],
            options={
                'db_table': 'email_logs',
                'indexes': [models.Index(fields=['email_type', 'recipient'], name='email_logs_email_t_c34ec2_idx')],
            },
        ),
    ]
